\PassOptionsToPackage{unicode=true}{hyperref} % options for packages loaded elsewhere
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provides euro and other symbols
\else % if luatex or xelatex
  \usepackage{unicode-math}
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage[]{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\usepackage{hyperref}
\hypersetup{
            pdftitle={correlation and Simple Regression Assignment},
            pdfauthor={Pradeep Paladugula},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

% set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother


\title{correlation and Simple Regression Assignment}
\author{Pradeep Paladugula}
\date{6/11/2020}

\begin{document}
\maketitle

\begin{verbatim}
1. When do we want to use correlation rather than using ANOVA? Please provide an example.
Answer: Correlation and ANOVA either of the analysis does not assume dependence of any variable on other variable, neither does they tries to find out the relationship between the two. It simply estimates the degree of association between variables. For both the analysis the values of dependent and independant variables are random. But we use correaltion over ANOVA when we test interdependence of association between variables. 


2. Please explain why partial correlation is useful and provide an example.
definition: A correlation between two variables in which the effects of other variables are held constant is knownas partial Correlation. I can conduct Partial Correlation with more than just 1 third-variable. I can include as many thrid-variables as I wish for the analysis. PCor explains how variables work together to explain patterns in the data. When multiple regression is taken in to consideration it explains how individual variable explain the relationship.

example: in The below data, the score relates to total happines score which is a constant variable and variance accounted by the Perceptions of corruption and variance accounted by the GDP per capita score. And also unique variance accounted by the both the variables for the Happiness score.
What regions rank the highest in overall score of happiness and each of the two factors contributing to happiness.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(ggm)}
\KeywordTok{library}\NormalTok{(reprex)}
\NormalTok{happinessscore <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{'datasets-894-813759-2019.csv'}\NormalTok{)}
\CommentTok{#vgsalesNew <- na.omit(vgsales)}
\KeywordTok{head}\NormalTok{(happinessscore)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Overall.rank Country.or.region Score GDP.per.capita Social.support
## 1            1           Finland 7.769          1.340          1.587
## 2            2           Denmark 7.600          1.383          1.573
## 3            3            Norway 7.554          1.488          1.582
## 4            4           Iceland 7.494          1.380          1.624
## 5            5       Netherlands 7.488          1.396          1.522
## 6            6       Switzerland 7.480          1.452          1.526
##   Healthy.life.expectancy Freedom.to.make.life.choices Generosity
## 1                   0.986                        0.596      0.153
## 2                   0.996                        0.592      0.252
## 3                   1.028                        0.603      0.271
## 4                   1.026                        0.591      0.354
## 5                   0.999                        0.557      0.322
## 6                   1.052                        0.572      0.263
##   Perceptions.of.corruption
## 1                     0.393
## 2                     0.410
## 3                     0.341
## 4                     0.118
## 5                     0.298
## 6                     0.343
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{pcor}\NormalTok{(}\KeywordTok{c}\NormalTok{(}\StringTok{'GDP.per.capita'}\NormalTok{, }\StringTok{"Perceptions.of.corruption"}\NormalTok{,}\StringTok{'Score'}\NormalTok{), }\KeywordTok{var}\NormalTok{(happinessscore))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in var(happinessscore): NAs introduced by coercion
\end{verbatim}

\begin{verbatim}
## [1] -0.01285421
\end{verbatim}

\begin{verbatim}
3.  When should we use regression instead of ANOVA?
Answer:
  Differences:
  a) Regression: Regression modal is based on one more continuous predictor variable    
     ANOVA: ANOVA modal based on one or more categorical predictor variables
  b) Regression: Focuses on fixed or independent or continuous variables    
     ANOVA: Focuses on random variables
  C) Regression: Only single error term 
     ANOVA: Several error terms
  d) Regression: Used mainly for forecasting and predictions    
     ANOVA: Used mainly to determine if data from various groups have a common means or not
\end{verbatim}

\#e) regression: Francis Galton who coined the term `regression' in the
19th century \#ANOVA: ANOVA got wide popularity when Sir Ronald Fisher
included the term in his book `statistical methods for research workers'

\begin{verbatim}
4. Please explain the relationship between SStotal, SSregression and SSerror.
Answer:
  SStotal: The Sum of squares total is denoted as SST, It is the sqaured difference between the observed variable and its mean (dispersion of the obsered variables around mean, it is a mesure of the total variability of the dataset)
    
  SSregression: The Sum of Squares due to regression or SSR. It is the sum of difference betweent he predicted value and mean of the dipendent variable(the measure taht decsribes how well the line fits the data). If the value of SSR is equal to the SST, It means our regression model captures the observed variability and is perfect. 
    
  SSerror: The Sum of Squares error or SSE. The error is the difference between the observed variable and the predicted value. we usually want to minimize the error. smaller the error, the better the estimation power of regression. it is also called as residual sum of squares.
    
  The above three are mathematically related: SST = SSR + SSE
    
    

5. Please use the following data to build a regression model and write a summary. IV is sugar and DV is calories.
Sugar: 5, 8, 9, 10, 15, 18, 14, 17, 20, 22, 24, 26, 30 ,30, 32
Calories: 20, 30, 60, 70, 100, 95, 70, 83, 103, 112, 130, 80, 95, 130, 112
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Sugar <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{5}\NormalTok{, }\DecValTok{8}\NormalTok{, }\DecValTok{9}\NormalTok{, }\DecValTok{10}\NormalTok{, }\DecValTok{15}\NormalTok{, }\DecValTok{18}\NormalTok{, }\DecValTok{14}\NormalTok{, }\DecValTok{17}\NormalTok{, }\DecValTok{20}\NormalTok{, }\DecValTok{22}\NormalTok{, }\DecValTok{24}\NormalTok{, }\DecValTok{26}\NormalTok{, }\DecValTok{30}\NormalTok{ ,}\DecValTok{30}\NormalTok{, }\DecValTok{32}\NormalTok{)}
\NormalTok{Calories <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{20}\NormalTok{, }\DecValTok{30}\NormalTok{, }\DecValTok{60}\NormalTok{, }\DecValTok{70}\NormalTok{, }\DecValTok{100}\NormalTok{, }\DecValTok{95}\NormalTok{, }\DecValTok{70}\NormalTok{, }\DecValTok{83}\NormalTok{, }\DecValTok{103}\NormalTok{, }\DecValTok{112}\NormalTok{, }\DecValTok{130}\NormalTok{, }\DecValTok{80}\NormalTok{, }\DecValTok{95}\NormalTok{, }\DecValTok{130}\NormalTok{, }\DecValTok{112}\NormalTok{)}
\NormalTok{Data <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(Sugar, Calories)}

\CommentTok{#density plot to check non zero variaance}
\KeywordTok{plot}\NormalTok{(}\KeywordTok{density}\NormalTok{(Data}\OperatorTok{$}\NormalTok{Sugar))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Corr-simpleReg-assg_files/figure-latex/unnamed-chunk-2-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{((}\KeywordTok{density}\NormalTok{(Data}\OperatorTok{$}\NormalTok{Calories)))}

\CommentTok{#Homoscedasticity/linearity test: sccatter plot}
\KeywordTok{library}\NormalTok{(ggplot2)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Corr-simpleReg-assg_files/figure-latex/unnamed-chunk-2-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{scatterPlot <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ Data, }\KeywordTok{aes}\NormalTok{(Sugar, Calories))}
\NormalTok{scatterPlot }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_point}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{main =} \StringTok{'Heteroscedasticity or linearity test between Sugar and Calories'}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\includegraphics{Corr-simpleReg-assg_files/figure-latex/unnamed-chunk-2-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{##Normally Distributed Error}
\KeywordTok{qqnorm}\NormalTok{(Data}\OperatorTok{$}\NormalTok{Sugar, }\DataTypeTok{main =} \StringTok{"Normal Q-Q Plot of sugar"}\NormalTok{)}
\KeywordTok{qqline}\NormalTok{(Data}\OperatorTok{$}\NormalTok{Sugar)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Corr-simpleReg-assg_files/figure-latex/unnamed-chunk-2-4.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{qqnorm}\NormalTok{(Data}\OperatorTok{$}\NormalTok{Calories, }\DataTypeTok{main =} \StringTok{"Normal Q-Q Plot of calories"}\NormalTok{)}
\KeywordTok{qqline}\NormalTok{(Data}\OperatorTok{$}\NormalTok{Calories)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Corr-simpleReg-assg_files/figure-latex/unnamed-chunk-2-5.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{##Regression Model}
\NormalTok{model <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(Calories }\OperatorTok{~}\StringTok{ }\NormalTok{Sugar, }\DataTypeTok{data =}\NormalTok{ Data)}
\KeywordTok{summary}\NormalTok{(model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Calories ~ Sugar, data = Data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -28.332 -19.060   3.438  11.985  27.758 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  29.1542    12.4132   2.349 0.035315 *  
## Sugar         3.0453     0.6074   5.013 0.000237 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 19.56 on 13 degrees of freedom
## Multiple R-squared:  0.6591, Adjusted R-squared:  0.6329 
## F-statistic: 25.13 on 1 and 13 DF,  p-value: 0.0002373
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{##Model Plot}
\KeywordTok{plot}\NormalTok{(Calories }\OperatorTok{~}\StringTok{ }\NormalTok{Sugar, }\DataTypeTok{data =}\NormalTok{ Data)}
\KeywordTok{abline}\NormalTok{(model)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Corr-simpleReg-assg_files/figure-latex/unnamed-chunk-2-6.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(model)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Corr-simpleReg-assg_files/figure-latex/unnamed-chunk-2-7.pdf}
\includegraphics{Corr-simpleReg-assg_files/figure-latex/unnamed-chunk-2-8.pdf}
\includegraphics{Corr-simpleReg-assg_files/figure-latex/unnamed-chunk-2-9.pdf}
\includegraphics{Corr-simpleReg-assg_files/figure-latex/unnamed-chunk-2-10.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#regression Equation}
\CommentTok{#Y = 29.1542 + 3.0435X }
\end{Highlighting}
\end{Shaded}

I have conducted simple regression modal to predict the calories to the
amount of sugar intake. Their is no further adjustment made to the data.
A significant regression equation was found (F(1, 13) = 25.13, p =
0.0002373 \textless{} 0.001), with and Rsquare = 0.66). Both intercept(p
= 0.04 \textless{} 0.05) and predictor(p \textless{} 0.001) were
statiscally significant, which falls in 99.9\% area under the curve. I
observed from the residual vs fitted plot this linear model is not
appropriate and Normal QQ plot of the theoritical quantiles and
standardized residuals are linear or they are nearly normal to my
predictions because the ouliers in the cooks distance graph are inside
the average cooks distnace values.

\end{document}
